### ISSUE TITLE
[question] Why does thumbnailQueueWorker start a new RCCService instance after 5 renders?

### ISSUE THREAD

**Issue by Redusofficial** [InnitGroup/syntaxsource#1]
I noticed that [thumbnailQueueWorker](https://github.com/InnitGroup/syntaxsource/blob/main/syntaxgameserver/main.py#L155) terminates the current 2020 instance then replaces it if there's been >= 5 renders created. Assuming you're a developer/owner of syntax, what is the reason for this?

https://github.com/InnitGroup/syntaxsource/blob/main/syntaxgameserver/main.py#L462

**Comment by InnitGroup** [comment]
Hello There!
No, I am not a developer or the owner of syntax.
well i am just going to assume that check was made for reducing cpu/ram usage etc etc...  and to maybe leave room? or maybe its just something with 2020 RCC... i am not quite sure...

**Comment by Redusofficial** [comment]
> Hello There! No, I am not a developer or the owner of syntax. well i am just going to assume that check was made for reducing cpu/ram usage etc etc... and to maybe leave room? or maybe its just something with 2020 RCC... i am not quite sure...

Ok, thank you.
